language: c

compiler: gcc

before_install:
  - sudo apt-get install csh
  - sudo apt-get install gfortran

install:
  - export WPHASE_HOME=$TRAVIS_BUILD_DIR
  - cd ${WPHASE_HOME}/src
  - pwd
  - make

script:
  - ${WPHASE_HOME}/bin/wpinversion    -h
  - ${WPHASE_HOME}/bin/wpinversion_gs -h
  - cd $TRAVIS_BUILD_DIR
  - wget http://wphase.unistra.fr/run_test.tgz
  - tar xvzf run_test.tgz
  - cd run_test
  - ./run_test.csh

notifications:
  email:
    recipients:
      - zacharie.duputel@unistra.fr
      - luis.rivera@unistra.fr
